// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lTmHMUfcQrLQ2qD8hX-b77Zga3tjocw',
    appId: '1:75251107189:web:7f4900397bdf29b8037f3c',
    messagingSenderId: '75251107189',
    projectId: 'connect-app-17f5f',
    authDomain: 'connect-app-17f5f.firebaseapp.com',
    storageBucket: 'connect-app-17f5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZta1269aLwHniO4cmj6fVOtvn104PqGo',
    appId: '1:75251107189:android:9a0c91fc59821d2d037f3c',
    messagingSenderId: '75251107189',
    projectId: 'connect-app-17f5f',
    storageBucket: 'connect-app-17f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1rC-QfEjPJjrWJtbn9O32B_x1INPIPo',
    appId: '1:75251107189:ios:5496397970b682ce037f3c',
    messagingSenderId: '75251107189',
    projectId: 'connect-app-17f5f',
    storageBucket: 'connect-app-17f5f.appspot.com',
    iosClientId: '75251107189-5sn2k35pdo80uiavomf6rhplblp93fg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectApp',
  );
}
